# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        python_version: ["3.6", "3.7", "3.8", "3.9"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Lint with flake8
        run: |
          poetry run flake8 bip44 --exit-zero --count --show-source --statistics

      - name: Test with pytest
        run: |
          poetry run pytest --cov=bip44 --cov-report xml

      - name: Upload to codecov
        uses: codecov/codecov-action@v1
