name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Test with pytest
        run: |
          pytest

      - name: Publish
        env:
          TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build

          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi "$TEST_PYPI_TOKEN"
          poetry config pypi-token.pypi "$PYPI_TOKEN"

          poetry publish --repository testpypi
          poetry publish
